// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADfeID4pocA-Vckk2_3yvrvnYmtwsVHs',
    appId: '1:871475854085:web:d91f11c9525ba8292bd56c',
    messagingSenderId: '871475854085',
    projectId: 'chat-app-ae612',
    authDomain: 'chat-app-ae612.firebaseapp.com',
    storageBucket: 'chat-app-ae612.appspot.com',
    measurementId: 'G-EHMV7XXTGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSu6VHp9yrN82PHNoOUUeMU3_q2_k1g1U',
    appId: '1:871475854085:android:1810f43a7a521d4f2bd56c',
    messagingSenderId: '871475854085',
    projectId: 'chat-app-ae612',
    storageBucket: 'chat-app-ae612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxgwqC8eS08gmTJmhAx05l5CJ-N5c5BmA',
    appId: '1:871475854085:ios:6b90bbe9b8a1d2f62bd56c',
    messagingSenderId: '871475854085',
    projectId: 'chat-app-ae612',
    storageBucket: 'chat-app-ae612.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxgwqC8eS08gmTJmhAx05l5CJ-N5c5BmA',
    appId: '1:871475854085:ios:6b90bbe9b8a1d2f62bd56c',
    messagingSenderId: '871475854085',
    projectId: 'chat-app-ae612',
    storageBucket: 'chat-app-ae612.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAADfeID4pocA-Vckk2_3yvrvnYmtwsVHs',
    appId: '1:871475854085:web:5f620ab9ed4473172bd56c',
    messagingSenderId: '871475854085',
    projectId: 'chat-app-ae612',
    authDomain: 'chat-app-ae612.firebaseapp.com',
    storageBucket: 'chat-app-ae612.appspot.com',
    measurementId: 'G-G5PJ72QPT5',
  );
}
